### ISSUE TITLE
Modding and API related tracking issue

### ISSUE THREAD

**Issue by copygirl** [anegostudios/VintageStory-Issues#218]
This is a tracking issue to collect and discuss bugs, features and requests regarding modding, the modding API and user experience regarding mods.

Feel free to also suggest smaller things that you think don't need their own issue (or you're just too lazy) right here in this issue. I will include them in the list as well.

## User experience
- [ ] #4 - Per-world mod selection
- [ ] #137 - Mod and server sub-menus should have more space

## Code mod related (API) requests
- [ ] #72 is still looking for an `OnEntityRecieveDamageEvent`.
- [ ] #115 - Give mods access to changing the HUD.
- [ ] #128 - Add ability to mark behaviors as optional
- [ ] #208 - Add events for (player) entity left/right click or attack/interact
- [ ] #211 - Add "HotbarSlotChanged" event which can be cancelled

## Content / Theme mod related (Asset / JSON) requests
- [ ] #97 - change json entity drops to include item pools
- [ ] #145 - json texture rotation
- [ ] #148 - Journal expansion

## Improvements and fixes
- [ ] #92 - Don't load universal mods on the client side if the server is not loading them
- [ ] #217 - Implement and use proper BlockPos, Vector, Matrix structs and similar
- [ ] Make sure `WatchedAttributes` also syncs on sub-tree changes

**Comment by copygirl** [comment]
I've already put my own smaller change regarding `WatchedAttributes` not syncing everything automatically as one might expect, I'd also like to add a way to prevent players from sprinting somehow, though I'm not entirely sure how. Perhaps add a `CanSprint` property to `EntityProperties`? (Which would then also affect the ability for hostile mobs to run at you like wolves and hyenas.)

**Comment by CreativeMD** [comment]
Another suggestion would be to rename the `AssetCategory` `entities` to `entitytypes` to make things consistent (as there is `blocktypes` and `itemtypes`).

**Comment by copygirl** [comment]
> * `arrow`, `spear` and `thrownstone` should use variantgroups instead of confusing alternate texture mapping.

Can you explain to me how that's related to modding / API changes? Sorry, I'm just not familiar with the JSON API so I don't know variants well and haven't seen the alternate texture mappings.

**Comment by Novocain1** [comment]
Requesting an OnCreatedByCrafting() callback for items.

**Comment by tenabraex** [comment]
Please implement tiling textures (x repeat, y repeat, no repeat) for better ability to brick, wall, etc. on large objects without using large textures.

**Comment by tenabraex** [comment]
per tonyliberatto - tabbed/dropdown etc. for mods in the creative menu (and I would add in things like the knapping and claymolding menus)

**Comment by Craluminum2413** [comment]
Gun magazine mechanics (also rate of fire and reload speed), that is, the ability to put several ammo into the weapon at once, having the ability to replenish ammunition at any time

**Comment by copygirl** [comment]
@Craluminum2413 Sounds like something that should be handled by a library mod.

**Comment by Craluminum2413** [comment]
What about the ammo selection? Round menu or etc. To select the desired arrows for the bow, for example

**Comment by copygirl** [comment]
Library mod, or base it on the tool mode selection GUI.

**Comment by tels-git** [comment]
Requesting a callback when things are crafted (first two are most important):
* in a barrel
* in a pitkiln
* in a steel furnace

**Comment by sekelsta** [comment]
Going to close this, because having a combined tracking issue does not seem useful.
 - Callback after things are crafted: If you still need this, please make a pull request or open a new issue.
 - Rename the `AssetCategory` `entities` to `entitytypes`: Let's not do that. It would be a major change disruptive to many many mods, for little gain.
 - Make sure `WatchedAttributes` also syncs on sub-tree changes: Technically a suggestion, though a good one.
