### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by Craluminum2413** [anegostudios/VintageStory-Issues#831]
- [ ] Lanterns should return clear quartz when you replace it with glass
- [ ] Crocks should display `Sealed` state in the shelf
- [ ] #889 - The second mode of shears for harvesting leaves and glow worms
- [ ] #933 - Butchering animals in vegetation
- [ ] #946 - Add `Pileable`, `Shelvable`, `Displaycaseable`, `Liquid` to items description, which are set to `true` for these values
- [ ] #963 - Add `shelvableMedium` and `shelvableLarge` shelves
- [ ] #990 - Remove iron meteorite piece from `stone path` and `Plumb and Square` recipes
- [ ] #1011 - Copy an entity with MMB
- [ ] #1036 - Name meals alphabetically
- [ ] #1017 - There are should be two variants for each basket, from papyrus and from reed
## Smithing
- [ ] #810 - Able to pick up the empty ingot mold if other is full of metal
- [ ] #916 - More slots for bloomery inventory
- [ ] #917 - Smelt a work item to the amount of ingots that were originally used
- [ ] #938 - Cast full metal blocks using clay molds
- [ ] #1042 - `/debug heldtemperature [arg]`
- [ ] When different fuels will have their own stats for forge, we must be able to place peat in the forge
### One step closer to get rid of crafting grid
- [ ] #909 - Tools making using an iron anvil making mechanics
- [ ] #936 - Make dough from flour with a simple Shift + RMB click on the barrel / bucket

**Comment by sirStroam** [comment]
No longer supporting suggestions/enhancements here. Please move to forum suggestions.
https://www.vintagestory.at/forums/forum/5-suggestions/
